=== Aptivi/Nitrocid/public/Nitrocid/Resources/Schemas/SettingsSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Settings Schema",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "Name": {
                "type": "string"
            },
            "Desc": {
                "type": "string"
            },
            "DisplayAs": {
                "type": "string"
            },
            "Keys": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "Name": {
                            "type": "string"
                        },
                        "Type": {
                            "type": "string"
                        },
                        "Variable": {
                            "type": "string"
                        },
                        "NKS_SHELL_SHELLS_UESH_LSCONFIGS_DESC": {
                            "type": "string"
                        },
                        "Masked": {
                            "type": "boolean"
                        },
                        "IsEnumeration": {
                            "type": "boolean"
                        },
                        "SelectionFunctionName": {
                            "type": "string"
                        },
                        "SelectionFunctionType": {
                            "type": "string"
                        },
                        "IsSelectionFunctionDict": {
                            "type": "boolean"
                        },
                        "SelectionFunctionArgs": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "ArgType": {
                                        "type": "string"
                                    },
                                    "ArgValue": {
                                        "type": "string"
                                    }
                                }
                            }
                        },
                        "SelectionFallback": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "EnumerationInternal": {
                            "type": "boolean"
                        },
                        "Enumeration": {
                            "type": "string"
                        },
                        "EnumerationAssembly": {
                            "type": "string"
                        },
                        "EnumerationZeroBased": {
                            "type": "boolean"
                        },
                        "UnsupportedPlatforms": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "IsValuePath": {
                            "type": "boolean"
                        },
                        "IsPathCurrentPath": {
                            "type": "boolean"
                        },
                        "DelimiterVariable": {
                            "type": "string"
                        },
                        "DelimiterVariableType": {
                            "type": "string"
                        },
                        "ShellType": {
                            "type": "string"
                        },
                        "MinimumValue": {
                            "type": "number"
                        },
                        "MaximumValue": {
                            "type": "number"
                        },
                        "Delimiter": {
                            "type": "string"
                        },
                        "ValuePathType": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "Name",
                        "Type"
                    ]
                }
            }
        },
        "required": [
            "Name",
            "Desc",
            "Keys"
        ]
    }
}

=== Aptivi/Nitrocid/public/Nitrocid.Base/Resources/Settings/SettingsEntries.json
[
    {
        "Name": "General",
        "Desc": "NKS_SETTINGS_KERNEL_GENERAL_DESC",
        "DisplayAs": "NKS_SETTINGS_KERNEL_GENERAL_DISPLAYAS",
        "Keys": [
            {
                "Name": "NKS_SETTINGS_KERNEL_GENERAL_LICENSEBOX_NAME",
                "Type": "SBoolean",
                "Variable": "ShowLicenseInfoBox",
                "Description": "NKS_SETTINGS_KERNEL_GENERAL_LICENSEBOX_DESC"
            },
            {
                "Name": "NKS_SETTINGS_KERNEL_GENERAL_CULTUREANDLANGUAGE_NAME",
                "Type": "SMultivar",
                "Description": "NKS_SETTINGS_KERNEL_GENERAL_CULTUREANDLANGUAGE_DESC",
                "Variables": [
                    {
                        "Name": "NKS_SETTINGS_KERNEL_GENERAL_CULTUREANDLANGUAGE_LANGUAGE_NAME",
                        "Type": "SSelection",
                        "Variable": "CurrentLanguage",
                        "IsEnumeration": false,
                        "SelectionFunctionName": "GetCultureCodes",
                        "SelectionFunctionType": "CultureManager",
                        "SelectionFallback": [ "en-US" ],
                        "Description": "NKS_SETTINGS_KERNEL_GENERAL_CULTUREANDLANGUAGE_LANGUAGE_DESC"
                    },
                    {
                        "Name": "NKS_SETTINGS_KERNEL_GENERAL_CULTUREANDLANGUAGE_CULTURE_NAME",
                        "Type": "SSelection",
                        "Variable": "CurrentCultureName",
                        "IsEnumeration": false,
                        "SelectionFunctionName": "GetCultureCodes",
                        "SelectionFunctionType": "CultureManager",
                        "SelectionFallback": [ "en-US" ],
                        "Description": "NKS_SETTINGS_KERNEL_GENERAL_CULTUREANDLANGUAGE_CULTURE_DESC"
                    }
                ]
            },
            {
                "Name": "NKS_SETTINGS_KERNEL_GENERAL_TIMEDATE_NAME",
                "Type": "SMultivar",
                "Description": "NKS_SETTINGS_KERNEL_GENERAL_TIMEDATE_DESC",
                "Variables": [
                    {
                        "Name": "NKS_SETTINGS_KERNEL_GENERAL_TIMEDATE_SYSTIMEZONE_NAME",
                        "Type": "SBoolean",
                        "Variable": "UseSystemTimeZone",
                        "Description": "NKS_SETTINGS_KERNEL_GENERAL_TIMEDATE_SYSTIMEZONE_DESC"
                    },
                    {
                        "Name": "NKS_SETTINGS_KERNEL_GENERAL_TIMEDATE_KERNELWIDETIMEZONE_NAME",
                        "Type": "SSelection",
                        "Variable": "KernelWideTimeZone",
                        "IsEnumeration": false,
                        "SelectionFunctionName": "GetTimeZoneNames",
                        "SelectionFunctionType": "TimeZones",
                        "SelectionFallback": [ "Etc/UTC", "GMT" ],
                        "Description": "NKS_SETTINGS_KERNEL_GENERAL_TIMEDATE_KERNELWIDETIMEZONE_DESC"
                    }
                ]
            },
            {
                "Name": "NKS_SETTINGS_KERNEL_GENERAL_BOOTLOADER_NAME",
                "Type": "SMultivar",
                "Description": "NKS_SETTINGS_KERNEL_GENERAL_BOOTLOADER_DESC",
                "Variables": [
                    {
                        "Name": "NKS_SETTINGS_KERNEL_GENERAL_BOOTLOADER_STYLE_NAME",
                        "Type": "SString",
                        "Variable": "BootStyle",
                        "Description": "NKS_SETTINGS_KERNEL_GENERAL_BOOTLOADER_STYLE_DESC"
                    },
                    {
                        "Name": "NKS_SETTINGS_KERNEL_GENERAL_BOOTLOADER_TIMEOUT_NAME",
                        "Type": "SIntSlider",
                        "Variable": "BootSelectTimeoutSeconds",
                        "Description": "NKS_SETTINGS_KERNEL_GENERAL_BOOTLOADER_TIMEOUT_DESC",
                        "MinimumValue": 0,
                        "MaximumValue": 600
                    },
                    {
                        "Name": "NKS_SETTINGS_KERNEL_GENERAL_BOOTLOADER_SELECT_NAME",
                        "Type": "SInt",
                        "Variable": "BootSelect",
                        "Description": "NKS_SETTINGS_KERNEL_GENERAL_BOOTLOADER_SELECT_DESC"
                    }
                ]
            },
            {
                "Name": "NKS_SETTINGS_KERNEL_GENERAL_HOMEPAGE_NAME",
                "Type": "SMultivar",
                "Description": "NKS_SETTINGS_KERNEL_GENERAL_HOMEPAGE_DESC",
                "Variables": [
                    {
                        "Name": "NKS_SETTINGS_KERNEL_GENERAL_HOMEPAGE_ENABLE_NAME",
                        "Type": "SBoolean",
                        "Variable": "EnableHomepage",
                        "Description": "NKS_SETTINGS_KERNEL_GENERAL_HOMEPAGE_ENABLE_DESC"
                    },
                    {
                        "Name": "NKS_SETTINGS_KERNEL_GENERAL_HOMEPAGE_ENABLEWIDGETS_NAME",
                        "Type": "SBoolean",
                        "Variable": "EnableHomepageWidgets",
                        "Description": "NKS_SETTINGS_KERNEL_GENERAL_HOMEPAGE_ENABLEWIDGETS_DESC"
                    },
                    {
                        "Name": "NKS_SETTINGS_KERNEL_GENERAL_HOMEPAGE_ENABLEFEED_NAME",
                        "Type": "SBoolean",
                        "Variable": "EnableHomepageRssFeed",
                        "Description": "NKS_SETTINGS_KERNEL_GENERAL_HOMEPAGE_ENABLEFEED_DESC"
                    },
                    {
                        "Name": "NKS_SETTINGS_KERNEL_GENERAL_HOMEPAGE_WIDGET_NAME",
                        "Type": "SSelection",
                        "Variable": "HomepageWidget",
                        "IsEnumeration": false,
                        "SelectionFunctionName": "GetWidgetNames",
                        "SelectionFunctionType": "WidgetTools",
                        "SelectionFallback": [ "AnalogClock" ],
                        "Description": "NKS_SETTINGS_KERNEL_GENERAL_HOMEPAGE_WIDGET_DESC"
                    }
                ]
            },
            {
                "Name": "NKS_SETTINGS_KERNEL_GENERAL_KERNELUPDATE_NAME",
                "Type": "SMultivar",
                "Description": "NKS_SETTINGS_KERNEL_GENERAL_KERNELUPDATE_DESC",
                "Variables": [
                    {
                        "Name": "NKS_SETTINGS_KERNEL_GENERAL_KERNELUPDATE_CHECKUPDATES_NAME",
                        "Type": "SBoolean",
                        "Variable": "CheckUpdateStart",
                        "Description": "NKS_SETTINGS_KERNEL_GENERAL_KERNELUPDATE_CHECKUPDATES_DESC"
                    }
                ]
            },
            {
                "Name": "NKS_SETTINGS_KERNEL_GENERAL_KERNELERROR_NAME",
                "Type": "SMultivar",
                "Description": "NKS_SETTINGS_KERNEL_GENERAL_KERNELERROR_DESC",
                "Variables": [
                    {
                        "Name": "NKS_SETTINGS_KERNEL_GENERAL_KERNELERROR_NOTIFY_NAME",
                        "Type": "SBoolean",
                        "Variable": "NotifyFaultsBoot",
                        "Description": "NKS_SETTINGS_KERNEL_GENERAL_KERNELERROR_NOTIFY_DESC"
                    },
                    {
                        "Name": "NKS_SETTINGS_KERNEL_GENERAL_KERNELERROR_SHOWSTACKTRACE_NAME",
                        "Type": "SBoolean",
                        "Variable": "ShowStackTraceOnKernelError",
                        "Description": "NKS_SETTINGS_KERNEL_GENERAL_KERNELERROR_SHOWSTACKTRACE_DESC"
                    }
                ]
            },
            {
                "Name": "NKS_SETTINGS_KERNEL_GENERAL_KERNELPOWER_NAME",
                "Type": "SMultivar",
                "Description": "NKS_SETTINGS_KERNEL_GENERAL_KERNELPOWER_DESC",
                "Variables": [
                    {
                        "Name": "NKS_SETTINGS_KERNEL_GENERAL_KERNELPOWER_NOAPMSIM_NAME",
                        "Type": "SBoolean",
                        "Variable": "SimulateNoAPM",
                        "Description": "NKS_SETTINGS_KERNEL_GENERAL_KERNELPOWER_NOAPMSIM_DESC"
                    },
                    {
                        "Name": "NKS_SETTINGS_KERNEL_GENERAL_KERNELPOWER_BEEP_NAME",
                        "Type": "SBoolean",
                        "Variable": "BeepOnShutdown",
                        "Description": "NKS_SETTINGS_KERNEL_GENERAL_KERNELPOWER_BEEP_DESC"
                    },
                    {
                        "Name": "NKS_SETTINGS_KERNEL_GENERAL_KERNELPOWER_DELAY_NAME",
                        "Type": "SBoolean",
                        "Variable": "DelayOnShutdown",
                        "Description": "NKS_SETTINGS_KERNEL_GENERAL_KERNELPOWER_DELAY_DESC"
                    }
                ]
            }
        ]
    },
    {
        "Name": "Colors",
        "Desc": "NKS_SETTINGS_KERNEL_COLORS_DESC",
        "DisplayAs": "NKS_SETTINGS_KERNEL_COLORS_DISPLAYAS",
        "Keys": [
            {
                "Name": "NKS_SETTINGS_KERNEL_COLORS_ACCENT_NAME",
                "Type": "SBoolean",
                "Variable": "UseAccentColors",
                "Description": "NKS_SETTINGS_KERNEL_COLORS_ACCENT_DESC"
            },
            {
                "Name": "NKS_SETTINGS_KERNEL_COLORS_FGACCENT_NAME",
                "Type": "SColor",
                "Variable": "AccentForegroundColor",
                "Description": "NKS_SETTINGS_KERNEL_COLORS_FGACCENT_DESC"
            },
            {
                "Name": "NKS_SETTINGS_KERNEL_COLORS_BGACCENT_NAME",
                "Type": "SColor",
                "Variable": "AccentBackgroundColor",
                "Description": "NKS_SETTINGS_KERNEL_COLORS_BGACCENT_DESC"
            },
            {
                "Name": "NKS_SETTINGS_KERNEL_COLORS_CONSOLEPALETTE_NAME",
